### ISSUE TITLE
--max-cores option would be nice

### ISSUE THREAD

**Issue by fabian20ro** [tmohme/gradle-elm-plugin#1]
I tried to use the plugin and compilation took a lot of time on travis-ci infrastructure for the hello world example. I see [here ](https://github.com/elm-lang/elm-compiler/issues/1473) that the fix is to add parameter --max-cores=<some number>.

Another nice improvement would be to be able to add any other additional parameters to the elm-make command.

Thanks for the nice work until now :+1:

**Comment by tmohme** [comment]
Thank you for your praise & suggestion. Generally I'll be glad to enhance the plugin's functionality.  
But as I understand the [elm-compiler issue](https://github.com/elm-lang/elm-compiler/issues/1473) you mentioned, this flag is still in discussion (the issue is open). Also I don't see any hint for this flag in the sources of [elm-make](https://github.com/elm-lang/elm-make/blob/master/src/Flags.hs).  
Do you have some (big enough) example for me to try this out?

What kind of additional parameters do you want to give to `elm-make`?  
I thought the only one `elm-make` accepts the the plugin doesn't is `--warn`.

**Comment by fabian20ro** [comment]
Somehow I thought --max-cores was already implemented. Regarding unimplemented options, I see there's also the --docs option (I have 0.18.0).
